### PR TITLE
Update v2 SC2 datasets

### PR DESCRIPTION
**Pull request by corneliusroemer**
Can be tested here: 
- https://clades.nextstrain.org/?dataset-url=gh:nextstrain/nextclade_data@2024-01-15-sc2-v2@/data/datasets/sars-cov-2-21L/references/BA.2/versions/2024-01-15T12:00:00Z/files
-  https://clades.nextstrain.org/?dataset-url=gh:nextstrain/nextclade_data@2024-01-15-sc2-v2@/data/datasets/sars-cov-2/references/MN908947/versions/2024-01-15T12:00:00Z/files

### CODE REVIEW

**Comment by rneher** [comment]
JN.4 seems to be in the wrong place? 
image

**Comment by corneliusroemer** [comment]
> JN.4 seems to be in the wrong place?
Good spotting. It's supposed to be there and has been there for as long as it's been in datasets. It's the name that is wrong (maybe should be BA.2.86.6), or the definition of BA.2.86.1 should not include the non-shared JN.4 mutation

**Comment by rneher** [comment]
I see. Thanks. I didn't see anything else that looked odd.

**Comment by corneliusroemer** [comment]
I added a small note to the changelog that this will be the last v2 SC2 update just in case.

v3 update to follow shortly

**Pull request merged**
