### PR TITLE
Add first draft of a tutorial for how to make your own reference dataset

### PR DESCRIPTION
**Pull request by sidneymbell**
Per conversation with @corneliusroemer -- here's a (very) rough draft of a walkthrough of how to go about making a reference dataset for a new pathogen on nextclade. You'll see there are still some pieces where I'm fuzzy on the details, but hopefully this is a good starting point? :) 

Not sure where you want this -- figured a draft PR was a good spot to get some eyes on it and then we can file it away wherever you'd like. Lmk if/when you'd like me to close it out or move it elsewhere.

### CODE REVIEW

**Comment by sidneymbell** [comment]
Alright, this is in pretty good shape at this point. Lmk if there's a better spot for this to live.

**Comment by ivan-aksamentov** [comment]
I am not competent to judge the dataset itself, but in terms of the tutorial:

It is fine and won't hurt to include, although seems to be a mixture of 3 things that, I believe might be beter to be separated.

 - how to build a tree - this is not Nextclade's business - we might just link to Augur and give a few short hints
 - how to get the rest of **dataset files** right - the files of the dataset itself, the inputs to Nextclade. Here I'd just say to use the existing datasets as a template and fix stuff inside. The improvement to this stage may come from actually documenting the inputs better in Nextclade docs.
 - how to include the dataset into `index_v2.json` to make it visible to the users of Nextclade Web and Nextclade CLI. This currently involves creating a particular directory tree, a `dataset.json`, a `datasetRef.json`, then running `./scripts/rebuild` - none of this matters anymore - this is a legacy, system with hardcoded hierarchy of dataset -> particular reference -> version (tag). This system is not flexible enough but we never had time to reorganize the repo. You can follow this old system if it suits you, however you could also add your entries into `index_v2.json` any other way you like, without following the old quirks. If you look at `index_v2.json` (produced by `./scripts/rebuild`) its is pretty trivial. But there is no existing script for that and I believe every pathogen has it's own particularities, so each might require a dedicated "rebuilds" script why not.

**Comment by sidneymbell** [comment]
Thanks for taking a look @ivan-aksamentov ! 

### Building the tree
I agree that this is not strictly within the purview of nextclade. As such, though, I'd make the argument that new nextclade users shouldn't have to learn the detailed in's and out's of augur to get started with nextclade, particularly because the tree is a means to an end for most folks. Thus, providing a template snakemake file is hugely beneficial for those users. I did find that it took pretty extensive knowledge of augur to get it right. Examples of bits that could be tricky for the uninitiated, and are smoothed over by providing a simple template:
- Which `rule`s generate the nucleotide and amino acid mutations (`ancestral` vs `translate` behavior)
- How to name their metadata field for `clade_membership` inference, and how to correctly fill in missing data 
- Exporting the right fields to auspice

### Getting the dataset files right 
In theory, yes, just copying an existing dataset would be the easiest way to go. However, the officially supported datasets are all "maximalist" in the sense that they include a lot of advanced functionality. It was really difficult for me to figure out what parameters were actually required and what the file should look like. While I agree that more documentation of these files would help a lot, constructing a correctly formatted minimal file is actually a fair amount of work and trial and error if you don't know what you're doing -- I think it's worthwhile to provide these to users. 

### Contribution guide. 
I agree with you here -- let's nix this piece.

Curious what @corneliusroemer thinks as he'd initially solicited the tutorial / docs? :)

**Comment by ivan-aksamentov** [comment]
We now have `docs/` directory with guides and examples
https://github.com/nextstrain/nextclade_data/blob/master/docs/README.md

**Pull request closed without merging**
