### PR TITLE
Proposed introduction of Yimim-2023 to the community dataset for PRRSV2.

### PR DESCRIPTION
**Pull request by mazeller**
Proposed dataset for PRRSV2 nomenclature from [Yimim et al. 2023](https://doi.org/10.1128/spectrum.02916-23). Dataset  includes clades, dates, geographic locations, RFLPs, and vaccines.

### CODE REVIEW

**Comment by ivan-aksamentov** [comment]
Hi Michael @mazeller,

Thanks for submitting this dataset!

As you see, we are currently having problems with our automation, but once we figure out these technical difficulties, we'll return to this PR.

Upon quick look I noticed that there's both `examples.fasta` and `sequences.fasta`. I think we can keep only one of these files, right? We'd prefer to not store too much data in the repository - only what's necessary and the most representative example sequence. Otherwise it looks good to me from the technical standpoint.

**Comment by mazeller** [comment]
Hello Ivan @ivan-aksamentov, I have removed the `example.fasta` in favor of keeping the `sequence.fasta`. Please let me know if any other part needs to be tended too.

**Comment by ivan-aksamentov** [comment]
@mazeller I have merged this pull request and now the dataset is available on `master` deployment of Nextclade: https://master.clades.nextstrain.org

And it can be referred to by its path:
https://master.clades.nextstrain.org/?dataset-name=community/isuvdl/mazeller/prrsv2/orf5/yimim2023

Examples can be ran with:
https://master.clades.nextstrain.org/?dataset-name=community/isuvdl/mazeller/prrsv2/orf5/yimim2023&input-fasta=example

Could you please double-check that everything works okay. And if so, let me know and I'll release it to public.

**Comment by mazeller** [comment]
@ivan-aksamentov I have reviewed and everything appears correct and is working as expected.

**Comment by mazeller** [comment]
@ivan-aksamentov My apologies, my collaborator pointed out some information that should be changed in the README. Should I make a new pull request?

**Comment by ivan-aksamentov** [comment]
@mazeller Yes, please make a PR. Note that I had to force-push master branch a few times due to infra problems. You might need to hard-reset master branch in your fork.

**Pull request merged**
