### PR TITLE
Update: Technical corrections to the README

### PR DESCRIPTION
**Pull request by mazeller**
@ivan-aksamentov PR for minor corrections to README.

### CODE REVIEW

**Comment by ivan-aksamentov** [comment]
@mazeller Do you want to also change the path of the dataset? Currently it's

```
community/isuvdl/mazeller/prrsv2/orf5/yimim2023
```

I don't know much about the virus, but should `prrsv2` also be `prrsv22`?

The paths are used to uniquely identify datasets and they are impossible to change once released.

**Comment by ivan-aksamentov** [comment]
Oh, sorry, you changed `22` to `2`. I read it wrong. So no, the path should stay the same :)

**Comment by mazeller** [comment]
@ivan-aksamentov The path, and the virus are both supposed to be denoted as either `PRRSV2` or `PRRSV-2`. The 22 was a typo on my end that I sadly caught last minute. Please, keep it the same :) .

**Comment by ivan-aksamentov** [comment]
Okay. Now merged and it should appear in "master" app after the build is done: https://github.com/nextstrain/nextclade_data/actions/runs/7744315475/job/21117771821

**Pull request merged**
